const copy={
 th:{nav:{about:'เรื่องราว',members:'สมาชิก',music:'เพลง',live:'ไลฟ์'},hero:{eyebrow:"THAILAND'S FIRST BANDOL · EST. 2022",line:'เสียงคำราม · จังหวะไอดอล · จิตวิญญาณไทย',listen:'ฟังเพลงล่าสุด',live:'เข้าสู่โลกของเรา'},about:{kicker:'มากกว่าวงดนตรี มากกว่าไอดอล',title:'เมื่อความหนัก<br>ปะทะความสดใส',body:'DEADKAT คือ BANDOL วงแรกของไทย—การผสมระหว่างวงดนตรีและไอดอลที่หลอม Metalcore, J-Rock และอิเล็กทรอนิกส์ เข้ากับท่วงท่ารำและเครื่องดนตรีพื้นบ้านไทย',quote:'“เราไม่เลือกว่าจะหนักหรือน่ารัก เราเป็นทั้งสองอย่าง”',founded:'ก่อตั้ง',people:'สมาชิก',singles:'ซิงเกิล',languages:'ภาษา'},members:{title:'MEET THE KATS'},music:{title:'TURN IT LOUD',intro:'หกบทเพลง หกโลกที่เชื่อมความดุดันเข้ากับเมโลดี้และรากวัฒนธรรมไทย'},culture:{kicker:'FROM THAILAND TO THE WORLD',title:'รากไทย<br>เสียงสากล',body:'พิณ แคน หนังตะลุง มโนราห์ และผ้าไทย ไม่ได้เป็นเพียงเครื่องประดับ แต่เป็นส่วนหนึ่งของภาษาเสียงและภาพของ DEADKAT ที่เดินทางไปพร้อมกับวงในทุกเวที'},live:{title:'NO QUIET NIGHTS',intro:'จากกรุงเทพฯ สู่ไทเปและไทจง—ทุกเวทีคือพื้นที่ปล่อยพลังเต็มพิกัด'},closing:{top:'THAI-BORN · WORLD-BOUND',cta:'BLACKAT RECORDS ↗'},footer:{note:'BANDOL FROM BANGKOK, THAILAND'}},
 en:{nav:{about:'About',members:'Members',music:'Music',live:'Live'},hero:{eyebrow:"THAILAND'S FIRST BANDOL · EST. 2022",line:'FERAL VOICES · IDOL PULSE · THAI SOUL',listen:'Hear the latest',live:'Enter our world'},about:{kicker:'MORE THAN A BAND. MORE THAN IDOLS.',title:'HEAVY MEETS<br>BRIGHT',body:"DEADKAT is Thailand's first BANDOL—a collision of band and idol energy. Metalcore, J-Rock and electronics meet Thai dance gestures and traditional instruments.",quote:'“We never choose between heavy and cute. We are both.”',founded:'Founded',people:'Members',singles:'Singles',languages:'Languages'},members:{title:'MEET THE KATS'},music:{title:'TURN IT LOUD',intro:'Six songs. Six worlds connecting full-force heaviness with melody and the roots of Thai culture.'},culture:{kicker:'FROM THAILAND TO THE WORLD',title:'THAI ROOTS.<br>GLOBAL NOISE.',body:"Phin, khaen, shadow puppetry, Manora dance and Thai textiles aren't decoration. They are part of DEADKAT's visual and sonic language on every stage."},live:{title:'NO QUIET NIGHTS',intro:'From Bangkok to Taipei and Taichung—every stage is a place to unleash everything.'},closing:{top:'THAI-BORN · WORLD-BOUND',cta:'BLACKAT RECORDS ↗'},footer:{note:'BANDOL FROM BANGKOK, THAILAND'}},
 ja:{nav:{about:'ストーリー',members:'メンバー',music:'音楽',live:'ライブ'},hero:{eyebrow:'タイ初のBANDOL · 2022年結成',line:'咆哮 · アイドルの鼓動 · タイの魂',listen:'最新曲を聴く',live:'私たちの世界へ'},about:{kicker:'バンド以上。アイドル以上。',title:'激しさと<br>輝きの衝突',body:'DEADKATはタイ初の「BANDOL」。バンドとアイドルのエネルギーを融合し、メタルコア、J-Rock、エレクトロニックサウンドにタイ舞踊や伝統楽器を重ねます。',quote:'「激しさか、可愛さか。選ばない。私たちは両方。」',founded:'結成',people:'メンバー',singles:'シングル',languages:'言語'},members:{title:'MEET THE KATS'},music:{title:'TURN IT LOUD',intro:'6つの楽曲、6つの世界。圧倒的な重さとメロディ、タイ文化のルーツをつなぐ。'},culture:{kicker:'FROM THAILAND TO THE WORLD',title:'タイのルーツ。<br>世界へ響く音。',body:'ピン、ケーン、影絵芝居、マノーラ舞踊、タイの織物。それらは装飾ではなく、すべてのステージを旅するDEADKATの音とビジュアルの言語です。'},live:{title:'NO QUIET NIGHTS',intro:'バンコクから台北、台中へ。すべてのステージで、全力を解き放つ。'},closing:{top:'THAI-BORN · WORLD-BOUND',cta:'BLACKAT RECORDS ↗'},footer:{note:'BANDOL FROM BANGKOK, THAILAND'}}
};
copy.th.nav.strategy='แผนสู่สากล';
copy.en.nav.strategy='Global Plan';
copy.ja.nav.strategy='海外戦略';
copy.th.nav.analytics='สถิติ';copy.en.nav.analytics='Analytics';copy.ja.nav.analytics='分析';
copy.th.tour={kicker:'TOUR GALLERY · ON STAGE',title:'พลังสดจากทุกเวที'};
copy.en.tour={kicker:'TOUR GALLERY · ON STAGE',title:'LIVE ENERGY, EVERY STAGE'};
copy.ja.tour={kicker:'ツアーギャラリー · ON STAGE',title:'すべてのステージに宿る熱量'};
copy.th.concerts={localKicker:'EVENTS & CONCERTS · THAILAND',localTitle:'เวทีในประเทศไทย',intlKicker:'INTERNATIONAL CONCERTS · TAIWAN',intlTitle:'จากไทยสู่เวทีนานาชาติ',source:'รายละเอียด วัน สถานที่ ผู้เข้าร่วม และจำนวนผู้ติดตาม อ้างอิงจาก DEADKAT Proposal ใน Canva'};
copy.en.concerts={localKicker:'EVENTS & CONCERTS · THAILAND',localTitle:'HOME-GROUND STAGES',intlKicker:'INTERNATIONAL CONCERTS · TAIWAN',intlTitle:'THAILAND TO THE WORLD',source:'Dates, venues, attendance and follower figures sourced from the DEADKAT Proposal on Canva.'};
copy.ja.concerts={localKicker:'イベント＆コンサート · タイ',localTitle:'タイ国内のステージ',intlKicker:'海外コンサート · 台湾',intlTitle:'タイから世界の舞台へ',source:'日程、会場、来場者数、フォロワー数はCanva「DEADKAT Proposal」に基づきます。'};
copy.th.analytics={kicker:'CROSS-PLATFORM PERFORMANCE',title:'ตัวเลขที่<br>ส่งเสียงดัง',intro:'ภาพรวมผลตอบรับของ 6 ซิงเกิลจาก YouTube, Spotify และ Apple Music แสดงให้เห็นฐานผู้ฟังที่เติบโตและศักยภาพในการขยายตลาดต่างประเทศ',total:'ยอดรับชมและสตรีมรวม',catalog:'ซิงเกิลที่ติดตามผล',performance:'SONG PERFORMANCE',performanceNote:'ยอดรวมจากสามแพลตฟอร์ม',audience:'AUDIENCE ORIGIN',audienceNote:'สัดส่วนผู้ฟังตามภูมิภาค',overseas:'ผู้ฟังต่างประเทศ',note:'ข้อมูลอ้างอิงจากเอกสาร DEADKAT Proposal ใน Canva · ตัวเลขเป็น Snapshot ณ วันที่จัดทำเอกสาร'};
copy.en.analytics={kicker:'CROSS-PLATFORM PERFORMANCE',title:'NUMBERS<br>THAT ROAR',intro:'Performance across six singles on YouTube, Spotify and Apple Music demonstrates a growing audience and clear potential for international market expansion.',total:'TOTAL CROSS-PLATFORM PLAYS',catalog:'RELEASES TRACKED',performance:'SONG PERFORMANCE',performanceNote:'Combined plays across three platforms',audience:'AUDIENCE ORIGIN',audienceNote:'Listener share by market',overseas:'OVERSEAS',note:'Source: DEADKAT Proposal on Canva · Figures are a snapshot from the date the proposal was prepared.'};
copy.ja.analytics={kicker:'クロスプラットフォーム実績',title:'数字が示す<br>確かな熱量',intro:'YouTube、Spotify、Apple Musicにおける6作品の実績は、ファンベースの成長と海外市場拡大の可能性を示しています。',total:'3プラットフォーム総再生数',catalog:'集計対象作品',performance:'楽曲パフォーマンス',performanceNote:'3プラットフォーム合計',audience:'オーディエンス地域',audienceNote:'市場別リスナー構成',overseas:'海外リスナー',note:'出典：Canva「DEADKAT Proposal」· 数値は資料作成時点のスナップショットです。'};
copy.th.strategy={kicker:'ONE-YEAR MARKET EXPANSION · TAIWAN',title:'จากกรุงเทพฯ<br>สู่เวทีโลก',lead:'แผนขยายฐานแฟนต่างประเทศด้วยจุดแข็งที่ผสานศิลปะไทย ความเป็นสากล และความหลากหลายทางดนตรี ผ่านเพลง การแสดง แฟชั่น และคอนเทนต์สามภาษา',year:'ปี',langs:'ภาษา',pillars:'เสาหลัก PR',market:'ตลาดเป้าหมาย',roadmap:'ROADMAP / กลยุทธ์ขยายตลาด',audiences:'TARGET AUDIENCES / กลุ่มเป้าหมาย',nation:'THAI SOFT POWER / ส่งเสริมภาพลักษณ์ประเทศ',campaign:'TikTok / IG Reel Challenge ด้วยท่าเต้นที่ประยุกต์จากท่ารำไทย พร้อมของรางวัลจากประเทศไทยและกิจกรรมแฟนมีต',media:'PRESS AND EDITORIAL',mediaIntro:'แม้ DEADKAT ยังอยู่ในช่วงขยายฐานแฟน แต่ได้รับแรงสนับสนุนอย่างต่อเนื่องจากพันธมิตรสื่อที่ช่วยเพิ่มการรับรู้และผลักดันการเติบโตของวง',mediaSupportTitle:'MEDIA SUPPORT / พันธมิตรสื่อ',mediaSupportCopy:'แม้ว่า Deadkat จะเป็นวงดนตรีใหม่ที่ยังอยู่ในระหว่างการสร้างฐานแฟนคลับ แต่เรายังคงได้รับการสนับสนุนอย่างต่อเนื่องจากพันธมิตรสื่อที่เห็นถึงศักยภาพและแนวทางดนตรีที่โดดเด่นของเรา การสนับสนุนของสื่อต่าง ๆ มีบทบาทสำคัญในการขับเคลื่อนการเติบโตของวงอย่างมั่นคง และช่วยขยายการเข้าถึงของวง ซึ่งเรามีรายชื่อพันธมิตรสื่อ ดังนี้',reach:'ยอดเข้าถึงสื่อรวม'};
copy.en.strategy={kicker:'ONE-YEAR MARKET EXPANSION · TAIWAN',title:'FROM BANGKOK<br>TO THE WORLD',lead:'A one-year international growth plan built on DEADKAT’s fusion of Thai arts, global production and musical diversity—delivered through music, performance, fashion and three-language content.',year:'YEAR',langs:'LANGUAGES',pillars:'PR PILLARS',market:'TARGET MARKET',roadmap:'ROADMAP / MARKET EXPANSION',audiences:'TARGET AUDIENCES',nation:'THAI SOFT POWER / NATIONAL IMAGE',campaign:'A TikTok and IG Reels challenge based on choreography adapted from Thai dance, supported by prizes from Thailand and fan-meet activities.',media:'PRESS AND EDITORIAL',mediaIntro:'While DEADKAT is still growing its fanbase, continued support from established media partners expands awareness and provides a strong platform for international growth.',mediaSupportTitle:'MEDIA SUPPORT / PARTNERS',mediaSupportCopy:'Although Deadkat is a new band still in the process of building its fanbase, we continue to receive ongoing support from media partners who recognize our potential and distinctive musical direction. This media support plays an important role in driving the band’s steady growth and expanding our reach. Our media partners include:',reach:'COMBINED MEDIA REACH'};
copy.ja.strategy={kicker:'1年間の市場拡大計画 · 台湾',title:'バンコクから<br>世界の舞台へ',lead:'タイ文化、国際的な制作力、音楽的多様性を強みに、楽曲・ライブ・ファッション・3言語コンテンツを通じて海外ファンを開拓する1年間の成長計画。',year:'年間',langs:'言語',pillars:'PRの柱',market:'重点市場',roadmap:'ロードマップ / 海外市場拡大',audiences:'ターゲットオーディエンス',nation:'タイのソフトパワー / 国家イメージ',campaign:'タイ舞踊を応用した振付によるTikTok・IG Reelsチャレンジ。タイからの賞品とファンミーティングを組み合わせます。',media:'PRESS AND EDITORIAL',mediaIntro:'DEADKATはファンベースを拡大中ですが、有力メディアパートナーから継続的な支援を受け、海外展開に向けた認知基盤を築いています。',mediaSupportTitle:'MEDIA SUPPORT / メディアパートナー',mediaSupportCopy:'Deadkatはまだファンベースを構築している新しいバンドですが、私たちの可能性と独自の音楽性に注目するメディアパートナーから継続的な支援を受けています。各メディアのサポートは、バンドの着実な成長を後押しし、リーチを広げるうえで重要な役割を果たしています。主なメディアパートナーは以下の通りです。',reach:'メディア総リーチ'};
Object.assign(copy.th.strategy,{digitalProof:'DIGITAL PROOF & CREATIVE DIRECTION',tiktokProof:'TIKTOK · คอนเทนต์สั้นและการเข้าถึงจากทัวร์',instagramProof:'INSTAGRAM · ไลฟ์เพอร์ฟอร์แมนซ์และคอมมูนิตี้',merchProof:'GLOBAL MERCHANDISE · ของสะสมและโปสการ์ด',fashionProof:'VISUAL KEI × CYBERPUNK · ภาพลักษณ์สากล',communityProof:'CORE FANDOM · คอมมูนิตี้คนรุ่นใหม่',liveProof:'LIVE MUSIC · กลุ่มร็อกและอิเล็กทรอนิกส์',cultureProof:'การเชื่อมวัฒนธรรมไทย–เอเชีย',textileProof:'THAI TEXTILE · ทิศทางชุดแสดง',pantsProof:'CAT PANTS · สินค้าวัฒนธรรมออริจินัล'});
Object.assign(copy.en.strategy,{digitalProof:'DIGITAL PROOF & CREATIVE DIRECTION',tiktokProof:'TIKTOK · SHORT-FORM CONTENT & TOUR REACH',instagramProof:'INSTAGRAM · LIVE PERFORMANCE & COMMUNITY',merchProof:'GLOBAL MERCHANDISE · COLLECTIBLES & POSTCARDS',fashionProof:'VISUAL KEI × CYBERPUNK · GLOBAL IMAGE',communityProof:'CORE FANDOM · YOUTH COMMUNITY',liveProof:'LIVE MUSIC · ROCK & ELECTRONIC AUDIENCE',cultureProof:'THAI–ASIAN CULTURAL CROSSOVER',textileProof:'THAI TEXTILE · STAGE COSTUME DIRECTION',pantsProof:'CAT PANTS · ORIGINAL CULTURAL MERCHANDISE'});
Object.assign(copy.ja.strategy,{digitalProof:'デジタル実績＆クリエイティブ方針',tiktokProof:'TIKTOK · ショート動画とツアーリーチ',instagramProof:'INSTAGRAM · ライブ映像とコミュニティ',merchProof:'グローバル物販 · コレクタブル＆ポストカード',fashionProof:'VISUAL KEI × CYBERPUNK · 国際的イメージ',communityProof:'コアファンダム · 若者コミュニティ',liveProof:'ライブ音楽 · ロック＆エレクトロニック層',cultureProof:'タイとアジア文化のクロスオーバー',textileProof:'タイ織物 · ステージ衣装の方向性',pantsProof:'CAT PANTS · オリジナル文化商品'});
Object.assign(copy.th.strategy,{tech:'TECHNICAL RIDER / พร้อมสำหรับเวทีสากล',techIntro:'แผนผังเวทีและ Input List พร้อมสำหรับผู้จัดงานต่างประเทศ ช่วยลดเวลา Advance Production และประสานงานหน้างานได้ชัดเจน',techInputs:'ช่องสัญญาณ',techMonitors:'WIRELESS IEM',techReady:'X32 RACK MIXER',booking:'BOOKING & INTERNATIONAL ENQUIRIES'});
Object.assign(copy.en.strategy,{tech:'TECHNICAL RIDER / TOUR READY',techIntro:'A stage plot and input list prepared for international promoters, helping streamline advance production and on-site coordination.',techInputs:'INPUT LINES',techMonitors:'WIRELESS IEM',techReady:'X32 RACK MIXER',booking:'BOOKING & INTERNATIONAL ENQUIRIES'});
Object.assign(copy.ja.strategy,{tech:'テクニカルライダー / 海外公演対応',techIntro:'海外プロモーター向けに整理されたステージプロットと入力リストにより、事前制作と現場連携をスムーズにします。',techInputs:'入力ライン',techMonitors:'WIRELESS IEM',techReady:'X32 RACK MIXER',booking:'ブッキング・海外公演お問い合わせ'});

copy.zh={
 nav:{about:'樂團故事',members:'成員',music:'音樂',live:'現場演出',analytics:'數據',strategy:'國際計畫'},
 hero:{eyebrow:'泰國首支 BANDOL · 成立於 2022 年',line:'狂野嗓音 · 偶像脈動 · 泰國靈魂',listen:'聆聽最新作品',live:'進入我們的世界'},
 about:{kicker:'不只是樂團，也不只是偶像',title:'重型聲響<br>遇上耀眼能量',body:'DEADKAT 是泰國首支「BANDOL」——融合樂團與偶像能量，將 Metalcore、J-Rock 與電子音樂，結合泰國舞蹈動作及傳統樂器。',quote:'「我們不在重型與可愛之間做選擇，因為兩者都是我們。」',founded:'成立年份',people:'成員',singles:'單曲',languages:'語言'},
 members:{title:'MEET THE KATS'},
 music:{title:'TURN IT LOUD',intro:'六首歌，六個世界；以旋律連結強烈聲響與泰國文化根源。'},
 culture:{kicker:'FROM THAILAND TO THE WORLD',title:'泰國根源<br>世界聲響',body:'Phin、Khaen、皮影戲、Manora 舞與泰國織品並非裝飾，而是 DEADKAT 在每一座舞台上的聲音與視覺語言。'},
 live:{title:'NO QUIET NIGHTS',intro:'從曼谷到台北與台中——每一座舞台，都是我們全力釋放能量的地方。'},
 tour:{kicker:'巡演圖輯 · ON STAGE',title:'每座舞台的現場能量'},
 concerts:{localKicker:'活動與演唱會 · 泰國',localTitle:'泰國現場舞台',intlKicker:'國際演出 · 台灣',intlTitle:'從泰國走向國際舞台',source:'日期、場地、入場人數與追蹤數據取自 DEADKAT Proposal。'},
 analytics:{kicker:'跨平台表現',title:'會咆哮的<br>數字',intro:'六首單曲在 YouTube、Spotify 與 Apple Music 的表現，展現持續成長的聽眾基礎，以及拓展國際市場的明確潛力。',total:'跨平台總播放次數',catalog:'統計作品',performance:'歌曲表現',performanceNote:'三個平台合計播放次數',audience:'聽眾地區',audienceNote:'各市場聽眾占比',overseas:'海外聽眾',note:'資料來源：DEADKAT Proposal · 數字為企劃製作當時的統計快照。'},
 strategy:{kicker:'一年市場拓展計畫 · 台灣',title:'從曼谷<br>走向世界',lead:'以泰國藝術、國際製作力與多元音樂為核心，透過歌曲、演出、時尚及三語內容，推動 DEADKAT 一年的海外成長計畫。',year:'年',langs:'語言',pillars:'公關支柱',market:'目標市場',roadmap:'路線圖 / 市場拓展',audiences:'目標受眾',nation:'泰國軟實力 / 國家形象',campaign:'以泰國舞蹈動作改編的 TikTok／IG Reels 挑戰，搭配來自泰國的獎品及粉絲見面活動。',media:'PRESS AND EDITORIAL',mediaIntro:'DEADKAT 正持續擴大粉絲基礎，並獲得具影響力媒體夥伴的支持，為國際發展建立更強的認知度。',mediaSupportTitle:'MEDIA SUPPORT / 媒體夥伴',mediaSupportCopy:'雖然 Deadkat 仍是一支正在建立粉絲基礎的新樂團，但我們持續獲得媒體夥伴的支持。這些媒體看見了我們的潛力與鮮明的音樂方向，而他們的支持對樂團穩定成長、擴大觸及範圍扮演重要角色。我們的媒體夥伴如下：',reach:'媒體總觸及',digitalProof:'數位實績與創意方向',tiktokProof:'TIKTOK · 短影音與巡演觸及',instagramProof:'INSTAGRAM · 現場演出與社群',merchProof:'全球周邊 · 收藏品與明信片',fashionProof:'VISUAL KEI × CYBERPUNK · 國際形象',communityProof:'核心粉絲 · 青年社群',liveProof:'現場音樂 · 搖滾與電子樂受眾',cultureProof:'泰國與亞洲文化交流',textileProof:'泰國織品 · 舞台服裝方向',pantsProof:'CAT PANTS · 原創文化周邊',tech:'技術需求 / 國際巡演就緒',techIntro:'為海外主辦方整理舞台配置與輸入線路，讓演出前製與現場溝通更清楚。',techInputs:'輸入線路',techMonitors:'WIRELESS IEM',techReady:'X32 RACK MIXER',booking:'演出邀約與國際合作'},
 closing:{top:'源自泰國 · 走向世界',cta:'BLACKAT RECORDS ↗'},
 footer:{note:'來自泰國曼谷的 BANDOL'}
};
Object.assign(copy.th.about,{bioTitle:'เรื่องราวของ<br>DEADKAT',bioOrigin:'DEADKAT เป็นวงดนตรี BANDOL วงแรกของไทย—การผสมผสานระหว่างไอดอลและวงดนตรี ประกอบด้วยสมาชิก 7 คน ได้แก่ YOKO, SAORI, MION, ROSE, AIZU, KUROKI และ YEVS ก่อตั้งขึ้นในปี 2022 และปล่อยผลงานแล้ว 6 ซิงเกิล ได้แก่ “It’s Never Too Late,” “Fleeting Lights,” “VIOLENCE,” “Polaroid,” “Cat Worship” และผลงานล่าสุด “ให้มันเป็นตัวฉัน (Bear the Burden)” โดยทุกเพลงผลิตและสร้างสรรค์ภายใต้สังกัด BLACKAT RECORDS',bioStage:'DEADKAT มีเอกลักษณ์โดดเด่นบนเวทีจากการผสมองค์ประกอบที่แตกต่างกันอย่างลงตัว วงมีนักร้องหลัก 5 คนที่นำเสนอการแสดงเต็มพลัง ดุดัน แต่ยังคงเสน่ห์และความสดใส ถ่ายทอดผ่านการร้องและการเต้นที่เปี่ยมด้วยพลังงาน',bioSound:'ดนตรีของพวกเธอผสานอิเล็กทรอนิกส์และร็อกอย่างมีชีวิตชีวา สร้างซาวด์ที่กล้าหาญ มีสีสัน และเข้าถึงผู้ฟังได้หลากหลาย อีกหนึ่งจุดเด่นคือเนื้อเพลงสามภาษา—ไทย ญี่ปุ่น และอังกฤษ—ซึ่งช่วยขยายฐานผู้ฟังและทำให้ผลงานของ DEADKAT เข้าถึงผู้ฟังระดับนานาชาติ',bioVision:'การนำเสนอหลายภาษาไม่เพียงสะท้อนความหลากหลายทางวัฒนธรรมของวง แต่ยังเชื่อมโยงแฟนเพลงจากหลากหลายภูมิภาคและพื้นเพทางภาษา ความสามารถในการหลอมรวมองค์ประกอบที่แตกต่างให้เป็นการแสดงที่เป็นหนึ่งเดียวและน่าติดตาม คือหลักฐานของความยืดหยุ่นและความคิดสร้างสรรค์ของ DEADKAT ในฐานะศิลปิน'});
Object.assign(copy.en.about,{bioTitle:'THE STORY OF<br>DEADKAT',bioOrigin:'DEADKAT is Thailand’s first BANDOL—a fusion of idol and band—formed by seven members: YOKO, SAORI, MION, ROSE, AIZU, KUROKI and YEVS. Established in 2022, the group has released six singles: “It’s Never Too Late,” “Fleeting Lights,” “VIOLENCE,” “Polaroid,” “Cat Worship,” and the latest release, “ให้มันเป็นตัวฉัน (Bear the Burden).” Every song is produced and developed under BLACKAT RECORDS.',bioStage:'DEADKAT has a distinctive stage identity built by bringing contrasting elements together as one. Five lead vocalists deliver performances that are powerful and fierce, yet retain charm and brightness through high-energy singing and choreography.',bioSound:'Their music combines electronic and rock elements into a vivid, daring and colourful sound that can connect with a wide range of listeners. Another defining strength is the use of three languages—Thai, Japanese and English—which expands the audience and makes DEADKAT’s work accessible to international listeners.',bioVision:'The multilingual approach expresses the group’s cultural diversity while connecting fans across regions and language backgrounds. DEADKAT’s ability to unite varied influences into a cohesive, compelling performance demonstrates their versatility and creativity as artists.'});
Object.assign(copy.ja.about,{bioTitle:'DEADKATの<br>ストーリー',bioOrigin:'DEADKATは、アイドルとバンドを融合したタイ初の「BANDOL」。YOKO、SAORI、MION、ROSE、AIZU、KUROKI、YEVSの7人で構成されています。2022年に結成され、「It’s Never Too Late」「Fleeting Lights」「VIOLENCE」「Polaroid」「Cat Worship」、そして最新作「ให้มันเป็นตัวฉัน (Bear the Burden)」まで6枚のシングルを発表。すべての楽曲はBLACKAT RECORDSのもとで制作されています。',bioStage:'DEADKATは、異なる要素をひとつに融合した独自のステージ表現を持っています。5人のメインボーカルが、力強く激しいパフォーマンスの中に魅力と輝きを共存させ、エネルギッシュな歌とダンスで観客を引き込みます。',bioSound:'音楽はエレクトロニックとロックを躍動的に融合し、大胆で色彩豊か、幅広いリスナーに届くサウンドを生み出します。タイ語・日本語・英語の3言語による歌詞も大きな特徴で、国際的なオーディエンスとの接点を広げています。',bioVision:'多言語での表現は、グループの文化的多様性を示すだけでなく、地域や言語背景の異なるファンをつなぎます。多彩な要素を一体感のある魅力的なステージへ昇華する力は、アーティストとしての柔軟性と創造性を物語っています。'});
Object.assign(copy.zh.about,{bioTitle:'DEADKAT<br>完整故事',bioOrigin:'DEADKAT 是泰國首支「BANDOL」——融合偶像與樂團形式，由 YOKO、SAORI、MION、ROSE、AIZU、KUROKI 與 YEVS 七位成員組成。樂團成立於 2022 年，至今已推出六首單曲：《It’s Never Too Late》、《Fleeting Lights》、《VIOLENCE》、《Polaroid》、《Cat Worship》，以及最新作品《ให้มันเป็นตัวฉัน (Bear the Burden)》。所有歌曲皆由 BLACKAT RECORDS 製作與發行。',bioStage:'DEADKAT 的舞台特色來自多種反差元素的完整融合。五位主唱以充滿力量與衝擊感的演出為核心，同時保有魅力與明亮氣質，透過高能量歌唱及舞蹈吸引觀眾。',bioSound:'她們的音樂將電子與搖滾元素生動結合，打造大膽、鮮明且能與多元聽眾連結的聲響。另一項重要特色是使用泰語、日語與英語三種語言創作歌詞，進一步拓展聽眾，讓 DEADKAT 的作品更容易走向國際。',bioVision:'多語言呈現不只展現樂團的文化多樣性，也讓來自不同地區與語言背景的粉絲彼此連結。DEADKAT 能將多樣元素融合成統一而引人入勝的演出，證明她們身為藝術家的靈活度與創造力。'});

const prPlan={
 th:{roadmap:[['สร้างตัวตนในตลาดสากล','ออกซิงเกิลไทย–ญี่ปุ่น–อังกฤษ ร่วมงานกับค่ายหรือโปรดิวเซอร์ต่างชาติ และเข้าร่วมอีเวนต์ไอดอล/ร็อกในต่างประเทศ'],['ขยายผ่านดิจิทัล','เผยแพร่เบื้องหลัง ซ้อมเต้น และไลฟ์สไตล์พร้อมซับอังกฤษ/ญี่ปุ่นบน YouTube และ TikTok พร้อมชาเลนจ์เต้นและคอมมูนิตี้ Discord, Weverse หรือ FanCafe'],['ร่วมงานศิลปินต่างชาติ','ร่วมงานกับศิลปินร็อก ไอดอลอินดี้ญี่ปุ่น K-Band และศิลปินสากลจากค่ายอิสระ ผ่านเพลงร่วม ไลฟ์ และคอนเทนต์แลกเปลี่ยน'],['Merchandise ระดับโลก','เปิดร้านบน Etsy, Shopify หรือ Amazon Global พร้อมพัฒนาโปสเตอร์ลายอนิเมะและแฟชั่น Visual Kei / Cyberpunk'],['ชูความหลากหลายทางวัฒนธรรม','สื่อสารความเป็นไทยผ่านเครื่องดนตรีพื้นบ้าน แฟชั่น และคอนเทนต์อธิบายมโนราห์กับหนังตะลุงให้ผู้ชมต่างชาติเข้าใจ'],['กลยุทธ์ภาษา','ออกแบบเพลงให้ฮุกภาษาอังกฤษ เวิร์สภาษาญี่ปุ่น/ไทย และใส่ซับหลายภาษาในมิวสิกวิดีโอทุกครั้ง']],audience:[['15–30','วัยรุ่นและวัยทำงานตอนต้นที่เสพสื่อสูง ชอบ Metalcore, J-Rock, Visual Kei และ EDM-Rock'],['ROCK × ELECTRONIC','แฟนซาวด์หนักแต่ติดหู กลุ่มผู้ฟัง BABYMETAL, PassCode, Poppy, Bring Me The Horizon และ Kawaii Metal'],['IDOL CULTURE','แฟน J-pop/K-pop ที่สนใจคาแรกเตอร์สมาชิก ท่าเต้น แฟชั่น เบื้องหลัง และการเติบโตของวง'],['ASIAN CULTURE','ผู้ชื่นชอบอนิเมะ Visual Kei, J-fashion และวัฒนธรรมญี่ปุ่นทั้งในไทยและต่างประเทศ']],nation:[['Thai Movement','ประยุกต์ท่ารำไทยเข้ากับท่าเต้นและการแสดง เพื่อสื่อสารภาพลักษณ์ประเทศไทยผ่านเวทีโดยตรง'],['Thai Textile','ใช้ผ้าไทยในชุดแสดง และพัฒนา “กางเกงแมว” ที่ได้รับแรงบันดาลใจจากกางเกงช้างเป็นสินค้าของวง'],['Social Challenge','แคมเปญ #DEADKATInTaiwan / #DEADKATinTaipei ให้แฟนชาวไต้หวัน Cover ท่าเต้น พร้อมเสื้อวง กางเกงแมว และวิดีโอพิเศษพร้อมลายเซ็นเป็นรางวัล'],['Cultural Fan Meet','แนวคิดแฟนมีตวันที่ 6 มิถุนายนที่ Raohe Street Night Market พร้อมกิจกรรมวัฒนธรรมไทยและแจกกางเกงแมว']]},
 en:{roadmap:[['Build an international identity','Release Thai–Japanese–English singles, work with overseas labels and producers, and enter international idol and rock events.'],['Scale through digital','Publish subtitled behind-the-scenes, dance practice and lifestyle content on YouTube and TikTok; launch dance challenges and communities on Discord, Weverse or FanCafe.'],['Cross-border collaborations','Create songs, livestreams and exchange content with rock artists, Japanese indie idols, K-Bands and independent international acts.'],['Global merchandise','Open worldwide sales through Etsy, Shopify or Amazon Global with anime-style posters and Visual Kei / Cyberpunk fashion.'],['Lead with cultural diversity','Showcase Thai instruments and fashion, with accessible content explaining Manora and Nang Talung to international audiences.'],['A clear language strategy','Structure songs with English hooks and Japanese/Thai verses, supported by multilingual subtitles for every music-video release.']],audience:[['15–30','Highly engaged youth and young professionals drawn to Metalcore, J-Rock, Visual Kei and EDM-Rock.'],['ROCK × ELECTRONIC','Fans of heavy but hook-driven music such as BABYMETAL, PassCode, Poppy, Bring Me The Horizon and Kawaii Metal.'],['IDOL CULTURE','J-pop and K-pop audiences invested in member personalities, choreography, fashion, behind-the-scenes stories and artist growth.'],['ASIAN CULTURE','Anime, Visual Kei, J-fashion and Japanese-culture communities in Thailand and abroad.']],nation:[['Thai Movement','Adapt Thai classical dance gestures into choreography and performance, communicating Thailand’s identity directly onstage.'],['Thai Textile','Use Thai textiles in principal stage costumes and develop “cat pants,” inspired by iconic elephant pants, as original merchandise.'],['Social Challenge','Invite Taiwanese fans to cover Thai-inspired choreography via #DEADKATInTaiwan and #DEADKATinTaipei, with signed shirts, cat pants and exclusive videos as prizes.'],['Cultural Fan Meet','A June 6 fan-meet concept at Raohe Street Night Market featuring Thai cultural activities and DEADKAT cat-pants giveaways.']]},
 ja:{roadmap:[['国際的な存在感を確立','タイ語・日本語・英語のシングルを発表し、海外レーベルやプロデューサーと協業。海外のアイドル／ロックイベントへ出演します。'],['デジタルで拡大','英語・日本語字幕付きの舞台裏、ダンス練習、ライフスタイル動画をYouTubeとTikTokで発信。ダンスチャレンジとDiscord、Weverse、FanCafeのコミュニティも展開します。'],['海外アーティストとの協業','ロック、日本のインディーアイドル、K-Band、海外インディー勢と楽曲、配信、交換コンテンツを制作します。'],['グローバル物販','Etsy、Shopify、Amazon Globalを活用し、アニメ調ポスターやVisual Kei／Cyberpunk系ファッションを世界へ販売します。'],['文化的多様性を強みに','タイの伝統楽器とファッションを紹介し、マノーラや影絵芝居を海外ファンに解説するコンテンツを制作します。'],['明確な言語戦略','英語のフック、日本語・タイ語のヴァースを設計し、すべてのMVに多言語字幕を付けます。']],audience:[['15–30','Metalcore、J-Rock、Visual Kei、EDM-Rockを好み、SNS利用が活発な若者・若手社会人。'],['ROCK × ELECTRONIC','BABYMETAL、PassCode、Poppy、Bring Me The Horizon、Kawaii Metalのような重くキャッチーな音を好む層。'],['IDOL CULTURE','メンバーの個性、ダンス、ファッション、舞台裏、成長物語を楽しむJ-pop／K-popファン。'],['ASIAN CULTURE','タイ国内外のアニメ、Visual Kei、J-fashion、日本文化ファン。']],nation:[['Thai Movement','タイ舞踊の所作を振付とライブに取り入れ、ステージからタイの魅力を直接発信します。'],['Thai Textile','主要衣装にタイ織物を使用し、象パンツから着想したオリジナルの「猫パンツ」を商品化します。'],['Social Challenge','#DEADKATInTaiwan／#DEADKATinTaipeiで台湾ファンのカバーダンスを募集。サイン入りTシャツ、猫パンツ、限定動画を贈ります。'],['Cultural Fan Meet','6月6日にRaohe Street Night Marketでタイ文化体験と猫パンツ配布を組み合わせたファンミーティングを提案します。']]}
};
prPlan.zh={
 roadmap:[
  ['建立國際品牌定位','推出泰語、日語、英語內容，與海外唱片公司及製作人合作，並參與國際偶像與搖滾活動。'],
  ['擴大數位影響力','在 YouTube 與 TikTok 發布附多語字幕的幕後、舞蹈練習及生活內容，並經營舞蹈挑戰與 Discord、Weverse 或 FanCafe 社群。'],
  ['跨國藝人合作','與搖滾樂團、日本地下偶像、K-Band 及國際獨立藝人合作歌曲、直播與交流內容。'],
  ['全球周邊商品','透過 Etsy、Shopify 或 Amazon Global 銷售，發展動漫風海報及 Visual Kei／Cyberpunk 時尚商品。'],
  ['以文化多樣性為核心','透過泰國傳統樂器、服裝與易懂內容，向海外觀眾介紹 Manora 舞及 Nang Talung 皮影戲。'],
  ['三語溝通策略','歌曲以英語 Hook 搭配日語與泰語段落，音樂錄影帶及社群內容提供多語字幕。']
 ],
 audience:[
  ['15–30','喜愛 Metalcore、J-Rock、Visual Kei 與 EDM-Rock，且高度活躍於社群媒體的青年與年輕上班族。'],
  ['ROCK × ELECTRONIC','喜愛厚重但旋律鮮明聲響的樂迷，如 BABYMETAL、PassCode、Poppy、Bring Me The Horizon 與 Kawaii Metal 聽眾。'],
  ['IDOL CULTURE','重視成員個性、舞蹈、時尚、幕後故事與成長歷程的 J-pop／K-pop 粉絲。'],
  ['ASIAN CULTURE','台灣、泰國及海外的動漫、Visual Kei、J-fashion 與亞洲文化社群。']
 ],
 nation:[
  ['Thai Movement','將泰國古典舞動作融入編舞與現場演出，直接透過舞台傳達泰國形象。'],
  ['Thai Textile','主要舞台服裝採用泰國織品，並開發受泰國象褲啟發的原創「貓褲」周邊。'],
  ['Social Challenge','透過 #DEADKATInTaiwan 與 #DEADKATinTaipei 邀請台灣粉絲翻跳泰式編舞，贈送簽名服飾、貓褲與限定影片。'],
  ['Cultural Fan Meet','規劃在台北舉辦結合泰國文化體驗、粉絲交流及 DEADKAT 原創周邊的見面活動。']
 ]
};
const roadmapDeck={
 th:[
  {tag:'',title:'เป้าหมายในประเทศ',groups:[['เป้าหมายระยะสั้น 6 เดือน–1 ปี',['เพิ่มการมีส่วนร่วมของผู้ชม 50%','เพิ่มยอดขายสินค้าแฟนคลับ 25%','ขยายโอกาสการแสดงสดทั่วประเทศ']],['เป้าหมายระยะยาว 1–2 ปี',['ขึ้นแสดงในอีเวนต์ใหญ่ในประเทศ 5–10 งานต่อปี','จัดคอนเสิร์ตเดี่ยวเต็มรูปแบบ','ผลักดัน DEADKAT ให้เป็นศิลปินทางเลือกแนวหน้าของไทย']],['แนวทางดำเนินงานหลัก',['ปล่อยซิงเกิลใหม่ 2 เพลงพร้อมคอนเทนต์ภาพ','วางกลยุทธ์คอนเทนต์บนแพลตฟอร์มโซเชียล','ทำแคมเปญสินค้าแฟนคลับที่ออกแบบเพื่อแฟนเพลง','ร่วมมือกับคอมมูนิตี้ดนตรีในประเทศ','รักษาความต่อเนื่องของโชว์สดและการปรากฏตัวผ่านสื่อ']]]},
  {tag:'',title:'เป้าหมายต่างประเทศ',groups:[['เป้าหมายระยะสั้น 6 เดือน–1 ปี',['ขยายฐานแฟนต่างประเทศผ่านแคมเปญดิจิทัล','ได้รับคำเชิญอย่างน้อย 1 เทศกาลดนตรีต่างประเทศ','เพิ่มกลุ่มผู้ฟังสตรีมมิงจากต่างประเทศ']],['เป้าหมายระยะยาว 1–2 ปี',['ขึ้นแสดงในหลายเทศกาลทั่วเอเชียและยุโรป','สร้างโอกาสทัวร์ต่างประเทศอย่างต่อเนื่อง','มีตัวแทนดูแลการจองงานต่างประเทศ']],['แนวทางดำเนินงานหลัก',['สร้างโปรเจกต์ร่วมข้ามประเทศกับศิลปินในเอเชีย','ทำแคมเปญโซเชียลมีเดียเจาะกลุ่มเป้าหมายต่างประเทศ','ผลักดันงานประชาสัมพันธ์และสื่อดนตรีต่างประเทศ','ขยายช่องทางจัดจำหน่ายสินค้าแฟนคลับสู่ตลาดโลก']]]},
  {tag:'',title:'ตลาดเป้าหมาย: ไต้หวัน',groups:[['ทำไมต้องไต้หวัน?',['ไต้หวันมีฉากดนตรีทางเลือกและดนตรีอิสระที่แข็งแรงที่สุดแห่งหนึ่งในเอเชีย ผู้ชมเปิดรับโพสต์ฮาร์ดคอร์ อัลเทอร์เนทีฟร็อก และศิลปินที่มีภาพลักษณ์โดดเด่น']],['โอกาสสำคัญ',['วัฒนธรรมไลฟ์เฮาส์แข็งแรง','เป็นประตูสู่ตลาดดนตรีเอเชียวงกว้าง','มีเทศกาลโชว์เคสนานาชาติที่เคลื่อนไหวต่อเนื่อง','ผู้ฟังดนตรีทางเลือกเปิดรับสิ่งใหม่และหลากหลาย']],['เทศกาลเป้าหมาย',['EMERGE FEST','Taiwan Music Festival','Megaport Festival']]]},
  {tag:'',title:'ตลาดเป้าหมาย: ญี่ปุ่น',groups:[['ทำไมต้องญี่ปุ่น?',['ญี่ปุ่นยังเป็นหนึ่งในตลาดดนตรีใหญ่ที่สุดของโลก และมีผู้ชมเฉพาะทางสำหรับอัลเทอร์เนทีฟร็อก โพสต์ฮาร์ดคอร์ อีโม และศิลปินที่ขับเคลื่อนด้วยภาพลักษณ์']],['โอกาสสำคัญ',['แฟนเพลงมีกำลังซื้อสินค้าแฟนคลับต่อคนสูง','ระบบนิเวศดนตรีสดมีความแข็งแรงและเป็นระบบ','มีความเข้าใจและให้คุณค่ากับวัฒนธรรมทางเลือกเฉพาะทาง','มีศักยภาพต่อยอดเป็นโอกาสทัวร์ระยะยาว']],['เทศกาลเป้าหมาย',['Music Lane Okinawa']]]}
 ],
 en:[
  {tag:'',title:'Domestic Goals',groups:[['Short-term goals: 6 months–1 year',['Increase audience engagement by 50%','Grow merchandise sales by 25%','Expand live performance opportunities nationwide']],['Long-term goals: 1–2 years',['Perform at 5–10 major domestic events annually','Headline a full-scale solo concert','Establish DEADKAT as a leading alternative act in Thailand']],['Key Actions',['Release 2 new singles with visual content','Strategic content marketing across social platforms','Fan-focused merchandise campaigns','Collaboration with local music communities','Consistent live performances and media appearances']]]},
  {tag:'',title:'International Goals',groups:[['Short-term goals: 6 months–1 year',['Grow international fanbase through digital campaigns','Secure invitations to at least one international festival','Increase international streaming audience']],['Long-term goals: 1–2 years',['Perform at multiple festivals across Asia and Europe','Build sustainable international touring opportunities','Establish agency representation for overseas bookings']],['Key Actions',['Cross-border collaborations with artists in Asia','Targeted social media campaigns','International PR and music media outreach','Global merchandise distribution']]]},
  {tag:'',title:'Target Market: Taiwan',groups:[['Why Taiwan?',['Taiwan has one of Asia’s strongest alternative and independent music scenes, with audiences highly receptive to post-hardcore, alternative rock and visually distinctive artists.']],['Key Opportunities',['Strong live house culture','Gateway to Greater Asia music market','Active international showcase festivals','Open-minded alternative music audiences']],['Target Festivals',['EMERGE FEST','Taiwan Music Festival','Megaport Festival']]]},
  {tag:'',title:'Target Market: Japan',groups:[['Why Japan?',['Japan remains one of the world’s largest music markets and has a dedicated audience for alternative rock, post-hardcore, emo and visual-driven acts.']],['Key Opportunities',['High merchandise spending per fan','Established live music ecosystem','Strong appreciation for niche alternative culture','Potential for long-term touring opportunities']],['Target Festivals',['Music Lane Okinawa']]]}
 ],
 ja:[
  {tag:'',title:'国内目標',groups:[['短期目標：6か月〜1年',['オーディエンス・エンゲージメントを50%向上','マーチャンダイズ売上を25%向上','国内ライブ出演機会を全国へ拡大']],['長期目標：1〜2年',['国内主要イベントに年間5〜10本出演','フルスケールの単独公演を開催','DEADKATをタイの主要オルタナティブアクトとして確立']],['Key Actions',['ビジュアルコンテンツ付き新シングルを2曲リリース','SNS横断の戦略的コンテンツマーケティング','ファン重視のマーチャンダイズ施策','国内音楽コミュニティとの連携','継続的なライブ出演とメディア露出']]]},
  {tag:'',title:'海外目標',groups:[['短期目標：6か月〜1年',['デジタルキャンペーンで海外ファンを拡大','少なくとも1つの海外フェス出演招待を獲得','海外ストリーミング視聴者を増加']],['長期目標：1〜2年',['アジアとヨーロッパの複数フェスに出演','持続的な海外ツアー機会を構築','海外ブッキング向けエージェンシー体制を確立']],['Key Actions',['アジア圏アーティストとの越境コラボレーション','ターゲット型SNSキャンペーン','海外PRと音楽メディアへのアプローチ','グローバルな物販流通']]]},
  {tag:'',title:'ターゲット市場：台湾',groups:[['Why Taiwan?',['台湾はアジアでも強いオルタナティブ／インディペンデント音楽シーンを持ち、post-hardcore、alternative rock、視覚的個性の強いアーティストを受け入れる土壌があります。']],['Key Opportunities',['強いライブハウス文化','Greater Asia市場へのゲートウェイ','国際ショーケースフェスの活発さ','オルタナティブ音楽に開かれた観客']],['Target Festivals',['EMERGE FEST','Taiwan Music Festival','Megaport Festival']]]},
  {tag:'',title:'ターゲット市場：日本',groups:[['Why Japan?',['日本は世界有数の音楽市場であり、alternative rock、post-hardcore、emo、ビジュアル主導のアクトに熱心なリスナー層があります。']],['Key Opportunities',['ファン一人あたりの物販消費が高い','確立されたライブ音楽エコシステム','ニッチなオルタナティブ文化への理解','長期ツアー機会の可能性']],['Target Festivals',['Music Lane Okinawa']]]}
 ],
 zh:[
  {tag:'',title:'泰國國內目標',groups:[['短期目標：6 個月至 1 年',['提升觀眾互動 50%','周邊商品銷售成長 25%','擴大全國現場演出機會']],['長期目標：1–2 年',['每年演出 5–10 場大型國內活動','舉辦完整規模單獨演唱會','將 DEADKAT 建立為泰國代表性 alternative act']],['Key Actions',['推出 2 首新單曲與視覺內容','跨社群平台策略內容行銷','以粉絲為核心的周邊商品活動','與本地音樂社群合作','穩定現場演出與媒體曝光']]]},
  {tag:'',title:'海外目標',groups:[['短期目標：6 個月至 1 年',['透過數位活動擴大國際粉絲','至少取得一個國際音樂節邀請','提高海外串流聽眾']],['長期目標：1–2 年',['在亞洲與歐洲多個音樂節演出','建立可持續的海外巡演機會','建立海外 booking 的代理／agency 代表']],['Key Actions',['與亞洲藝人跨國合作','目標式社群媒體活動','國際 PR 與音樂媒體推廣','全球周邊商品流通']]]},
  {tag:'',title:'目標市場：台灣',groups:[['Why Taiwan?',['台灣擁有亞洲最強的 alternative 與 independent 音樂場景之一，聽眾高度接受 post-hardcore、alternative rock 以及視覺特色鮮明的藝人。']],['Key Opportunities',['強大的 live house 文化','通往大亞洲音樂市場的入口','活躍的國際 showcase 音樂節','開放的 alternative music 受眾']],['Target Festivals',['EMERGE FEST','Taiwan Music Festival','Megaport Festival']]]},
  {tag:'',title:'目標市場：日本',groups:[['Why Japan?',['日本仍是全球最大音樂市場之一，且擁有 alternative rock、post-hardcore、emo 與視覺導向藝人的固定受眾。']],['Key Opportunities',['粉絲周邊消費力高','成熟的現場音樂生態','重視小眾 alternative 文化','具備長期巡演機會']],['Target Festivals',['Music Lane Okinawa']]]}
 ]
};
const pressData={
 th:[
  {source:'ThaiPost',date:'26 มี.ค. 2024',title:'‘DEADKAT’ เซอร์ไพรส์ นำ “พิณกับแคน” และการ “แห่นางแมว” ผสมกันในซิงเกิลใหม่',body:'บทความพูดถึง “CAT WORSHIP” ซิงเกิลล่าสุดของ DEADKAT วง BANDOL วงแรกของไทย และการนำพิณ แคน กับวัฒนธรรมแห่นางแมวมาผสมในงานเพลง',url:'https://www.thaipost.net/entertainment-news/559196/'},
  {source:'LINE TODAY / KAZZ MAGAZINE',date:'29 เม.ย. 2024',title:'สัมภาษณ์ DEADKAT กับซิงเกิลใหม่ “CAT WORSHIP”',body:'บทสัมภาษณ์จาก KAZZ ที่นำเสนอ DEADKAT ในฐานะเกิร์ลกรุ๊ป BANDOL ที่น่าสนใจ และเล่าการเปิดตัวผลงาน CAT WORSHIP',url:'https://today.line.me/th/v3/article/Opz0x0v'},
  {source:'THE GUITAR MAG',date:'EDITORIAL QUOTE',title:'Creative intent worth watching',body:'“จริงอยู่สิ่งนี้อาจจะไม่ใช่เรื่องใหม่สำหรับวงการดนตรี แต่กับบ้านเราแล้วก็ไม่ใช่ว่าจะมีวงดนตรีสไตล์นี้ให้เห็นได้บ่อยๆ… ขอคารวะในความตั้งใจนี้”',url:''}
 ],
 en:[
  {source:'ThaiPost',date:'Mar 26, 2024',title:'DEADKAT surprises listeners by blending phin, khaen and Hae Nang Maew culture into a new single',body:'Coverage of “CAT WORSHIP” highlights DEADKAT as Thailand’s first BANDOL act and spotlights how the song brings Thai folk instruments and ritual imagery into a modern release.',url:'https://www.thaipost.net/entertainment-news/559196/'},
  {source:'LINE TODAY / KAZZ MAGAZINE',date:'Apr 29, 2024',title:'Interview with DEADKAT on the new single “CAT WORSHIP”',body:'A KAZZ interview presenting DEADKAT as a notable BANDOL girl group and discussing the release of CAT WORSHIP.',url:'https://today.line.me/th/v3/article/Opz0x0v'},
  {source:'THE GUITAR MAG',date:'EDITORIAL QUOTE',title:'Creative intent worth watching',body:'The Guitar Mag praised the intention, creativity and courage behind DEADKAT, noting that this kind of band is still rare in Thailand and requires both artists and back-end team to move together.',url:''}
 ],
 ja:[
  {source:'ThaiPost',date:'2024年3月26日',title:'DEADKAT、新曲でピン、ケーン、「雨乞いの猫行列」文化を融合',body:'「CAT WORSHIP」を取り上げ、タイ初のBANDOLであるDEADKATが民俗楽器と文化的イメージを現代的な楽曲に取り入れた点を紹介。',url:'https://www.thaipost.net/entertainment-news/559196/'},
  {source:'LINE TODAY / KAZZ MAGAZINE',date:'2024年4月29日',title:'新曲「CAT WORSHIP」についてのDEADKATインタビュー',body:'KAZZによるインタビュー。注目すべきBANDOLガールグループとしてDEADKATを紹介し、CAT WORSHIPのリリースに触れています。',url:'https://today.line.me/th/v3/article/Opz0x0v'},
  {source:'THE GUITAR MAG',date:'EDITORIAL QUOTE',title:'注目すべき創造性',body:'The Guitar Magは、DEADKATの意図、創造性、挑戦する姿勢を評価し、タイではまだ珍しいスタイルで、アーティストと制作チームが共に進む必要があると述べています。',url:''}
 ],
 zh:[
  {source:'ThaiPost',date:'2024 年 3 月 26 日',title:'DEADKAT 將 Phin、Khaen 與 Hae Nang Maew 文化融合進新單曲',body:'報導介紹《CAT WORSHIP》，強調 DEADKAT 作為泰國首支 BANDOL，如何把泰國民俗樂器與文化意象帶入現代作品。',url:'https://www.thaipost.net/entertainment-news/559196/'},
  {source:'LINE TODAY / KAZZ MAGAZINE',date:'2024 年 4 月 29 日',title:'DEADKAT 談新單曲《CAT WORSHIP》',body:'KAZZ 訪談將 DEADKAT 介紹為值得關注的 BANDOL 女團，並談到 CAT WORSHIP 的發行與作品概念。',url:'https://today.line.me/th/v3/article/Opz0x0v'},
  {source:'THE GUITAR MAG',date:'EDITORIAL QUOTE',title:'值得關注的創意企圖',body:'The Guitar Mag 肯定 DEADKAT 的企圖心、創造力與敢於呈現的態度，指出這類型樂團在泰國仍不常見，需要藝人與幕後團隊共同推動。',url:''}
 ]
};
const riderData={
 th:{band:['Drum - Kuroki','Bass - Yevs','Guitar - Raoul','VOC 1 - Yoko','VOC 2 - Saori','VOC 3 - Mion','VOC 4 - Aizu','VOC 5 - Rose'],inputs:['1. Kick','2. Sn Top','3. Sn Bot','4. Tom 1','5. Tom F','6. HH','7. OH HH','8. OH HH','9. Bass','10. GT','11. YOKO','12. SAORI','13. MION','14. AIZU','15. ROSE','16. DRUM EAR','17. DATA L','18. DATA R','19. METRONOME','20. Extra Line','21. Extra Line'],providedTitle:'รายการอุปกรณ์ที่ทางวงเตรียมมาเอง (Band Provided)',provided:['กีตาร์ไฟฟ้าและเบส','In-Ear Monitor','เอฟเฟกต์กีตาร์ไฟฟ้าและเบส','สแนร์และกระเดื่องกลอง','คอมพิวเตอร์โน้ตบุ๊กพร้อม Audio Interface สำหรับเปิด Data / Backing Track','สายแจ็คและสาย XLR สำหรับกีตาร์ รวมถึงระบบ Sub-Mixing สำหรับกลอง','มิกเซอร์ Behringer X32 Rack'],venueTitle:'รายการอุปกรณ์ที่ขอให้ผู้จัดงานเตรียม (Venue / Organizer Provided)',venue:['กลองชุดพร้อมฮาร์ดแวร์ ไม่รวมสแนร์และกระเดื่อง','ไมโครโฟนสำหรับกลองชุด','DI Box จำนวน 4 ตัว','สาย XLR สำหรับระบบสัญญาณ จำนวน 20 เส้น','Wireless Microphone จำนวน 5 ชุด','ลำโพง Front of House (FOH) ตามมาตรฐานของงาน','Wireless In-Ear Monitor จำนวน 8 ชุด หรืออย่างน้อย 5 ชุด','ปลั๊กไฟ 220V จำนวน 4 จุด แต่ละจุดมีอย่างน้อย 4 ช่องเสียบ','โต๊ะสำหรับคอมพิวเตอร์และ Data Playback จำนวน 1 ชุด'],note:'หมายเหตุ: ทางวงใช้มิกเซอร์ Behringer X32 Rack เป็นระบบหลักในการควบคุมเสียง และต้องการสัญญาณเชื่อมต่อกับระบบเสียงหลักของงานผ่านสาย XLR',engineer:'Sound Engineer · supunatkang@gmail.com · 063-047-9367'},
 en:{band:['Drum - Kuroki','Bass - Yevs','Guitar - Raoul','VOC 1 - Yoko','VOC 2 - Saori','VOC 3 - Mion','VOC 4 - Aizu','VOC 5 - Rose'],inputs:['1. Kick','2. Sn Top','3. Sn Bot','4. Tom 1','5. Tom F','6. HH','7. OH HH','8. OH HH','9. Bass','10. GT','11. YOKO','12. SAORI','13. MION','14. AIZU','15. ROSE','16. DRUM EAR','17. DATA L','18. DATA R','19. METRONOME','20. Extra Line','21. Extra Line'],providedTitle:'Band Provided',provided:['Electric guitar and bass','In-Ear Monitor','Electric guitar and bass effects','Snare and kick drum pedal','Laptop with Audio Interface for Data / Backing Track playback','Jack and XLR cables for guitar plus drum sub-mixing system','Behringer X32 Rack mixer'],venueTitle:'Venue / Organizer Provided',venue:['Drum kit with hardware, excluding snare and kick pedal','Drum microphones','4 DI Boxes','20 XLR signal cables','5 wireless microphone sets','FOH speaker system to event standard','8 wireless In-Ear Monitor sets, or at least 5 sets','4 points of 220V power, each with at least 4 outlets','1 table for computer and Data Playback equipment'],note:'Note: The band uses a Behringer X32 Rack as the main audio control system and requires XLR connection to the venue’s main sound system.',engineer:'Sound Engineer · supunatkang@gmail.com · 063-047-9367'},
 ja:{band:['Drum - Kuroki','Bass - Yevs','Guitar - Raoul','VOC 1 - Yoko','VOC 2 - Saori','VOC 3 - Mion','VOC 4 - Aizu','VOC 5 - Rose'],inputs:['1. Kick','2. Sn Top','3. Sn Bot','4. Tom 1','5. Tom F','6. HH','7. OH HH','8. OH HH','9. Bass','10. GT','11. YOKO','12. SAORI','13. MION','14. AIZU','15. ROSE','16. DRUM EAR','17. DATA L','18. DATA R','19. METRONOME','20. Extra Line','21. Extra Line'],providedTitle:'バンド持込機材',provided:['エレキギター、ベース','In-Ear Monitor','ギター／ベース用エフェクト','スネア、キックペダル','Data / Backing Track再生用ノートPCとAudio Interface','ギター用ジャック／XLRケーブル、ドラム用Sub-Mixingシステム','Behringer X32 Rackミキサー'],venueTitle:'会場／主催者側手配',venue:['ドラムセット一式（スネア、キックペダルを除く）','ドラム用マイク','DI Box 4台','XLR信号ケーブル20本','ワイヤレスマイク5セット','イベント規格に準じたFOHスピーカー','Wireless In-Ear Monitor 8セット、最低5セット','220V電源4か所、各4口以上','Data Playback用PC・機材を置くテーブル1台'],note:'注：バンドはBehringer X32 Rackをメイン音響制御システムとして使用し、会場メインPAへのXLR接続を必要とします。',engineer:'Sound Engineer · supunatkang@gmail.com · 063-047-9367'},
 zh:{band:['Drum - Kuroki','Bass - Yevs','Guitar - Raoul','VOC 1 - Yoko','VOC 2 - Saori','VOC 3 - Mion','VOC 4 - Aizu','VOC 5 - Rose'],inputs:['1. Kick','2. Sn Top','3. Sn Bot','4. Tom 1','5. Tom F','6. HH','7. OH HH','8. OH HH','9. Bass','10. GT','11. YOKO','12. SAORI','13. MION','14. AIZU','15. ROSE','16. DRUM EAR','17. DATA L','18. DATA R','19. METRONOME','20. Extra Line','21. Extra Line'],providedTitle:'樂團自備設備',provided:['電吉他與貝斯','In-Ear Monitor','電吉他與貝斯效果器','小鼓與大鼓踏板','用於 Data / Backing Track 播放的筆電與 Audio Interface','吉他用導線與 XLR 線，以及鼓組 Sub-Mixing 系統','Behringer X32 Rack 混音器'],venueTitle:'場地方／主辦方需準備',venue:['鼓組與硬體，不含小鼓及大鼓踏板','鼓組麥克風','DI Box 4 個','XLR 訊號線 20 條','無線麥克風 5 組','符合活動規格的 FOH 主喇叭系統','Wireless In-Ear Monitor 8 組，或至少 5 組','220V 電源 4 處，每處至少 4 個插座','Data Playback 電腦與設備用桌子 1 張'],note:'備註：樂團使用 Behringer X32 Rack 作為主要聲音控制系統，需透過 XLR 與場地主要音響系統連接。',engineer:'Sound Engineer · supunatkang@gmail.com · 063-047-9367'}
};
const members=[
 {name:'YOKO',role:'VOCALS / SCREAMER',handle:'yoko.deadkat',instagram:'2.4K',tiktok:'2.7K',photo:'members-new/yoko.jpg'},
 {name:'SAORI',role:'VOCALS / RAPPER',handle:'saori.deadkat',instagram:'989',tiktok:'2.7K',photo:'members-new/saori.jpg'},
 {name:'AIZU',role:'VOCALS',handle:'aizu.deadkat',instagram:'2.0K',tiktok:'668',photo:'members-new/aizu.jpg'},
 {name:'ROSE',role:'VOCALS / MAKNAE',handle:'rose.deadkat',instagram:'850',tiktok:'1.7K',photo:'members-new/rose.jpg'},
 {name:'KUROKI',role:'DRUMMER',handle:'kuroki.deadkat',instagram:'395',tiktok:'151',photo:'members-new/kuroki.jpg'},
 {name:'MION',role:'VOCALS / SUB RAPPER',handle:'mion.deadkat',instagram:'1.1K',tiktok:'1.1K',photo:'members-new/mion.jpg'},
 {name:'YEVS',role:'BASS',handle:'evxguczi',instagram:'1.1K',tiktok:'7.7K',photo:'members-new/yevs.jpg'}
];
const records={
 th:[['IT’S NEVER TOO LATE','ซิงเกิลเปิดตัวที่ผสม Metalcore อันเข้มข้นกับทำนองติดหูและอิทธิพล J-Rock'],['FLEETING LIGHTS','เมทัลคอร์สามภาษา ไทย ญี่ปุ่น อังกฤษ โปรดิวซ์ร่วมกับ Koji Hirachi'],['VIOLENCE','ซาวด์ฮาร์ดคอร์เมทัลทรงพลังที่ตอกย้ำตัวตนไอดอลสายร็อก'],['POLAROID','ซิงเกิลที่บันทึกวัฒนธรรม Cheki และความผูกพันระหว่างวงกับแฟนเพลง'],['CAT WORSHIP','พิณและแคนอีสานปะทะเมทัลคอร์ร่วมสมัยอย่างหนักแน่นและขี้เล่น'],['BEAR THE BURDEN','หนังตะลุงและมโนราห์จากภาคใต้ในโลกเมทัลสมัยใหม่และภาพจำยุค 90s']],
 en:[["IT’S NEVER TOO LATE",'A debut single where metalcore weight meets catchy melody and J-Rock influence.'],['FLEETING LIGHTS','Trilingual Thai, Japanese and English metalcore, co-produced with Koji Hirachi.'],['VIOLENCE','Hardcore-metal force that doubles down on the rock-idol identity.'],['POLAROID','A portrait of Cheki culture and the bond between the band and its fans.'],['CAT WORSHIP','Northeastern Thai phin and khaen collide with playful modern metalcore.'],['BEAR THE BURDEN','Southern shadow puppetry and Manora enter a modern metal world framed by 90s nostalgia.']],
 ja:[["IT’S NEVER TOO LATE",'メタルコアの重さとキャッチーなメロディ、J-Rockの影響が交差するデビュー曲。'],['FLEETING LIGHTS','タイ語・日本語・英語の3言語で歌うメタルコア。Koji Hirachiとの共同制作。'],['VIOLENCE','ロックアイドルとしての個性を刻む、力強いハードコア・メタル。'],['POLAROID','チェキ文化と、グループとファンの絆を映し出す一曲。'],['CAT WORSHIP','タイ東北部のピンとケーンが、遊び心ある現代メタルコアと衝突。'],['BEAR THE BURDEN','南部の影絵芝居とマノーラを、90年代の記憶と現代メタルに融合。']]
};
records.zh=[
 ["IT’S NEVER TOO LATE",'出道單曲，以強烈 Metalcore、抓耳旋律與 J-Rock 影響交織出 DEADKAT 的起點。'],
 ['FLEETING LIGHTS','以泰語、日語與英語演唱的三語 Metalcore 作品，與 Koji Hirachi 共同製作。'],
 ['VIOLENCE','充滿爆發力的 Hardcore Metal，進一步確立樂團偶像的鮮明定位。'],
 ['POLAROID','描繪 Cheki 拍立得文化，以及 DEADKAT 與粉絲之間的連結。'],
 ['CAT WORSHIP','泰國東北部 Phin 與 Khaen 傳統樂器，碰撞俏皮而現代的 Metalcore。'],
 ['BEAR THE BURDEN','將泰國南部皮影戲與 Manora 舞帶入現代金屬聲響，並融入 90 年代氛圍。']
];
const discographyEditorial={
 th:{
  kicker:'',
  title:'เสียงเพลงที่ขายได้ทั้งซาวด์<br>วัฒนธรรม และเรื่องเล่า',
  intro:'แต่ละซิงเกิลของ DEADKAT ถูกออกแบบให้เป็นมากกว่าเพลงโปรโมต—มันคือหลักฐานของตัวตน BANDOL ที่เชื่อมเมทัลคอร์ ไอดอล J-Rock ภาษา วัฒนธรรมไทย และภาพจำบนเวทีเข้าด้วยกัน',
  notes:[
   ['IT’S NEVER TOO LATE','หนึ่งในซิงเกิลเปิดตัวของ DEADKAT ที่สื่อถึงเอกลักษณ์ของวงอย่างชัดเจน ด้วยการผสมผสาน Metalcore เข้ากับความเบาลง เลือกใช้ทำนองติดหู และเสียงสมัยใหม่ที่ได้รับอิทธิพลจาก J-Rock เพื่อเปิดประตูให้ผู้ฟังทั้งสายหนักและสายเมโลดี้เข้าถึงวงได้พร้อมกัน'],
   ['FLEETING LIGHTS','ผลงานที่แสดงความสามารถของวงในการสร้างดนตรีเมทัลคอร์ที่ซับซ้อน หนักแน่น แต่ยังคงความสนุกในองค์ประกอบทางดนตรีและรูปแบบเสียงร้องที่หลากหลาย จุดเด่นคือเนื้อร้องสามภาษา ไทย ญี่ปุ่น และอังกฤษ ซึ่งช่วยขยายกลุ่มผู้ฟังสู่ตลาดนานาชาติ โดยมีการดูแลภาษาและโปรดักชันร่วมกับ Koji Hirachi โปรดิวเซอร์ที่มีผลงานร่วมกับกลุ่มไอดอลญี่ปุ่นอย่าง PASSCODE'],
   ['VIOLENCE','ซิงเกิลลำดับที่ 3 ที่ตอกย้ำความเป็นวงไอดอลสายร็อกของ DEADKAT การโปรดิวซ์โดย เอส จากวง KLUAYTHAI ช่วยเพิ่มมิติของซาวด์ให้เข้มข้นและทรงพลังขึ้น เป็นอีกก้าวสำคัญที่ผสมความเป็นไอดอลเข้ากับอิทธิพลของฮาร์ดคอร์เมทัลได้อย่างลงตัว'],
   ['POLAROID','ซิงเกิลลำดับที่ 4 ที่ไม่เพียงแสดงความหลากหลายของวง แต่ยังสะท้อนวัฒนธรรมไอดอลผ่านกิจกรรม Cheki หรือการถ่ายภาพโพลารอยด์ร่วมกับสมาชิก ซึ่งเป็นพื้นที่สร้างความผูกพันระหว่างแฟนคลับ โอตาคุ และตัวศิลปินอย่างใกล้ชิด'],
   ['CAT WORSHIP','เพลงที่มอบความแปลกใหม่ให้แนวเมทัลคอร์ ด้วยการผสมดนตรีพื้นบ้านภาคตะวันออกเฉียงเหนือของไทย โดยเฉพาะพิณและแคน เข้ากับโครงสร้างเมทัลคอร์ร่วมสมัย ทำให้เกิดซาวด์ที่ทั้งหนักแน่น ขี้เล่น และมีมิติจากซินธิไซเซอร์ที่เสริมความลึกและความเคลื่อนไหวให้บทเพลง'],
   ['BEAR THE BURDEN','ซิงเกิลลำดับที่ 6 ที่ขยายอัตลักษณ์ทางดนตรีไปสู่ภาคใต้ของไทย ผ่านหนังตะลุงและมโนราห์ที่ผสมกับเมทัลสมัยใหม่ มิวสิกวิดีโอเล่าสถานการณ์พนักงานออฟฟิศด้วยภาพย้อนยุคยุค 90s โดยสมาชิกวงมีส่วนร่วมในการออกแบบท่าเต้น ชุด และพัฒนาเนื้อเรื่องร่วมกับทีม Blackat Records'],
   ['THAI PERFORMANCE DNA','การแสดงของ DEADKAT มีส่วนผสมของดนตรีไทย ท่ารำไทยที่นำมาประยุกต์ และชุดที่ใช้ผ้าไทยเป็นองค์ประกอบ รวมถึง “กางเกงแมว” สินค้าที่วงผลิตเองและได้รับแรงบันดาลใจจากกางเกงช้าง สิ่งเหล่านี้ทำให้วงสามารถนำเสนอภาพลักษณ์ของประเทศไทยต่อผู้ชมต่างประเทศได้โดยตรงผ่านโชว์สด']
  ]
 },
 en:{
  kicker:'CANVA DISCOGRAPHY TEXT',
  title:'Songs built to pitch sound,<br>culture and story',
  intro:'DEADKAT’s singles are built as more than promotional tracks. Together they prove a BANDOL identity where metalcore, idol energy, J-Rock, multilingual writing, Thai culture and stage image work as one export-ready package.',
  notes:[
   ['IT’S NEVER TOO LATE','One of DEADKAT’s debut singles, this track clearly introduces the group’s identity by blending metalcore with a lighter, more accessible edge. Catchy melodies and modern sounds influenced by J-Rock open the door for both heavy-music listeners and melody-driven audiences.'],
   ['FLEETING LIGHTS','A standout work that shows the group’s ability to create complex, weighty metalcore while keeping the music fun through varied arrangements and vocal styles. Its Thai, Japanese and English lyrics expand the band’s reach internationally, with language and production support from Koji Hirachi, known for work connected to Japanese idol group PASSCODE.'],
   ['VIOLENCE','The third single reinforces DEADKAT’s rock-idol identity. Production by S from KLUAYTHAI adds greater intensity and power to the sound, marking an important step in fusing idol presence with hardcore-metal influence.'],
   ['POLAROID','The fourth single highlights the band’s versatility while reflecting idol culture through Cheki—polaroid-style photo sessions where fans, or otaku, can take photos with members and build a closer emotional bond with the artists.'],
   ['CAT WORSHIP','This track brings a fresh angle to metalcore by combining northeastern Thai folk music, especially phin and khaen, with contemporary metalcore structure. The result is heavy, playful and distinctive, with synthesizers adding depth and movement.'],
   ['BEAR THE BURDEN','The sixth single extends DEADKAT’s musical identity to southern Thailand through Nang Talung shadow puppetry and Manora dance fused with modern metal. The music video follows office-worker tension through a 90s-inspired visual world, with members contributing to choreography, costume design and story development alongside Blackat Records.'],
   ['THAI PERFORMANCE DNA','DEADKAT’s live performance incorporates Thai music, adapted Thai dance gestures and stage costumes using Thai textiles. The group also created “cat pants,” self-produced merchandise inspired by elephant pants, turning cultural identity into a direct onstage export signal for international audiences.']
  ]
 },
 ja:{
  kicker:'CANVA DISCOGRAPHY TEXT',
  title:'音、文化、物語を<br>ピッチできる楽曲群',
  intro:'DEADKATのシングルは、単なるプロモーション曲ではありません。メタルコア、アイドル性、J-Rock、多言語表現、タイ文化、ステージの視覚表現をひとつに結ぶ、海外展開に向けたBANDOLとしての証明です。',
  notes:[
   ['IT’S NEVER TOO LATE','DEADKATのデビュー期を代表する一曲。メタルコアを軸にしながら、より軽やかで入りやすい質感、耳に残るメロディ、J-Rockの影響を受けた現代的なサウンドを取り入れ、ラウド層とメロディ重視のリスナーの両方に届く入口を作っています。'],
   ['FLEETING LIGHTS','複雑で重厚なメタルコアを構築しつつ、アレンジと多彩なボーカルで楽しさを失わない、DEADKATの実力を示す楽曲。タイ語・日本語・英語の三言語詞により国際的なリーチを広げ、PASSCODE関連の実績を持つKoji Hirachiが言語面とプロダクション面を支えています。'],
   ['VIOLENCE','3rdシングルとして、ロックアイドルとしてのDEADKATの存在感をさらに強く打ち出す作品。KLUAYTHAIのSによるプロデュースがサウンドに厚みとパワーを加え、アイドル性とハードコアメタルの影響を自然に融合させています。'],
   ['POLAROID','4thシングル。バンドの多様性を示すだけでなく、メンバーとファンが一緒にポラロイド写真を撮る「チェキ」文化を通して、アイドルシーンならではの近い関係性を描いています。'],
   ['CAT WORSHIP','タイ東北部の民俗音楽、とくにピンとケーンを現代的なメタルコア構造に組み込んだ新鮮な楽曲。重さと遊び心が同居し、シンセサイザーが楽曲に深みと動きを加えています。'],
   ['BEAR THE BURDEN','6thシングルでは、南タイの影絵芝居「ナン・タルン」とマノーラ舞踊を現代メタルに融合。MVは90年代的なオフィスワーカーの世界観で構成され、振付、衣装、物語作りにメンバー自身もBlackat Recordsチームと共に参加しています。'],
   ['THAI PERFORMANCE DNA','DEADKATのライブには、タイ音楽、タイ舞踊を応用した振付、タイ織物を使ったステージ衣装が組み込まれています。さらに象パンツから着想した自主制作グッズ「猫パンツ」もステージに登場し、タイのイメージを直接海外の観客へ届けます。']
  ]
 },
 zh:{
  kicker:'CANVA DISCOGRAPHY TEXT',
  title:'以歌曲傳遞聲音、<br>文化與故事',
  intro:'DEADKAT 的單曲不只是宣傳作品；它們共同證明 BANDOL 身分：把 Metalcore、偶像能量、J-Rock、多語創作、泰國文化與舞台形象整合成適合國際市場的完整企劃。',
  notes:[
   ['IT’S NEVER TOO LATE','DEADKAT 出道初期的代表單曲之一。歌曲以 Metalcore 為核心，加入較輕盈、容易入口的聽感，搭配抓耳旋律與受 J-Rock 影響的現代聲響，讓重型音樂聽眾與旋律派聽眾都能進入 DEADKAT 的世界。'],
   ['FLEETING LIGHTS','這首作品展現樂團創作複雜、厚重 Metalcore 的能力，同時透過多樣編曲與聲線保留音樂的趣味性。歌詞使用泰語、日語與英語三種語言，擴大國際受眾；日英語與製作亦由曾與日本偶像團體 PASSCODE 相關作品合作的 Koji Hirachi 協力。'],
   ['VIOLENCE','第三張單曲進一步強化 DEADKAT 的搖滾偶像定位。由 KLUAYTHAI 的 S 擔任製作，讓聲音更具層次、強度與爆發力，是把偶像性與 Hardcore Metal 影響融合的重要一步。'],
   ['POLAROID','第四張單曲不只呈現樂團的多樣性，也透過 Cheki 拍立得合照文化描繪偶像場景：粉絲或 Otaku 能與成員合照，建立更近距離的情感連結。'],
   ['CAT WORSHIP','這首歌為 Metalcore 帶來新鮮角度，把泰國東北部民俗音樂，尤其是 Phin 與 Khaen，放入當代 Metalcore 結構中。成品兼具重量、玩心與獨特性，合成器也為歌曲增加深度與流動感。'],
   ['BEAR THE BURDEN','第六張單曲把 DEADKAT 的音樂身分延伸到泰國南部，將 Nang Talung 皮影戲與 Manora 舞融入現代金屬。MV 以 90 年代風格描繪辦公室員工壓力，成員也與 Blackat Records 團隊共同參與編舞、服裝與故事發展。'],
   ['THAI PERFORMANCE DNA','DEADKAT 的現場演出融合泰國音樂、改編自泰國舞蹈的動作，以及使用泰國織物的舞台服裝。樂團也自製受到象褲啟發的「貓褲」周邊，讓泰國文化形象能直接透過舞台傳遞給國際觀眾。']
  ]
 }
};
const recordLinks=[
 'https://youtu.be/rc1E0IYTnDk',
 'https://youtu.be/qbwmKDIOphs',
 'https://youtu.be/HNZLEnKvCDY',
 'https://youtu.be/8EcsLzkwDS4',
 'https://youtu.be/ED2433rY5_k',
 'https://bfan.link/beartheburden'
];
const recordCovers=['its-never-too-late.jpg','fleeting-lights.jpg','violence.jpg','polaroid.jpg','cat-worship.jpg','bear-the-burden.jpg'];
const streamingData=[
 {name:'CAT WORSHIP',yt:142300,sp:6193,am:62},
 {name:'VIOLENCE',yt:51664,sp:3911,am:549},
 {name:"IT’S NEVER TOO LATE",yt:39969,sp:7072,am:696},
 {name:'POLAROID',yt:39522,sp:17171,am:79},
 {name:'FLEETING LIGHTS',yt:34787,sp:6022,am:540},
 {name:'BEAR THE BURDEN',yt:17774,sp:1000,am:99}
].map(d=>({...d,total:d.yt+d.sp+d.am}));
const audienceLabels={th:[['ไทย',68],['ญี่ปุ่น',17],['ไต้หวัน',9],['อื่น ๆ',6]],en:[['Thailand',68],['Japan',17],['Taiwan',9],['Other',6]],ja:[['タイ',68],['日本',17],['台湾',9],['その他',6]],zh:[['泰國',68],['日本',17],['台灣',9],['其他地區',6]]};
const concertData={
 th:{local:[
  {date:'15 ต.ค. 2022',name:'PARADISE FEST 6',venue:'JJ MALL · กรุงเทพฯ',type:'เทศกาลเชิงพาณิชย์',audience:'5,000 คน',reach:'48K followers',poster:['paradise-fest-6.webp']},
  {date:'22 มี.ค. 2025',name:'RAMPAGE FESTIVAL 2025',venue:'THE STREET HALL · รัชดา กรุงเทพฯ',type:'เทศกาลเชิงพาณิชย์',audience:'500 คน',reach:'3.8K followers',poster:['rampage-festival.jpg']},
  {date:'17 พ.ค. 2025',name:'ROCK ALARM FESTIVAL 2025',venue:'WAREHOUSE STADIUM · คลองเตย กรุงเทพฯ',type:'เทศกาลเชิงพาณิชย์',audience:'5,000 คน',reach:'41K followers',poster:['rock-alarm-1.jpg','rock-alarm-2.jpg']}
 ],international:[
  {date:'7 มิ.ย. 2025',name:'櫻擊祭 2025 · PRIMULAV 2025',venue:'MEDIASPHERE THEATER · TAIPEI CITY, TAIWAN',type:'เทศกาลเชิงพาณิชย์ · POWERED BY MAH',audience:'500 คน',reach:'3.1K followers',poster:['primulav-2025.jpg']},
  {date:'8 มิ.ย. 2025',name:'IDOL CREAM SODA!! × MAH IN TAIWAN',venue:'MEDIASPHERE THEATER · TAIPEI CITY, TAIWAN',type:'เทศกาลเชิงพาณิชย์',audience:'500 คน',reach:'3.1K followers',poster:['idol-cream-soda.jpg']},
  {date:'23–24 ส.ค. 2025',name:'OURSEA CHILL FEST 2025',venue:'MITSUI OUTLET · TAICHUNG, TAIWAN',type:'เทศกาลเชิงพาณิชย์',audience:'10,000 คน',reach:'12.3K followers',poster:['oursea-chill-fest.webp']},
  {date:'10–12 ต.ค. 2025',name:'IDOL KINGDOM 2025',venue:'UNI-PRESIDENT DEPARTMENT STORE / MOONDOG, BREEZE CENTER · TAIPEI, TAIWAN',type:'เทศกาลเชิงพาณิชย์',audience:'5,000 คน',reach:'4K followers',poster:['idol-kingdom-1.webp','idol-kingdom-2.webp']}
 ]},
 en:{local:[
  {date:'15 OCT 2022',name:'PARADISE FEST 6',venue:'JJ MALL · BANGKOK, THAILAND',type:'COMMERCIAL FESTIVAL',audience:'5,000 ATTENDEES',reach:'48K FOLLOWERS',poster:['paradise-fest-6.webp']},
  {date:'22 MAR 2025',name:'RAMPAGE FESTIVAL 2025',venue:'THE STREET HALL · RATCHADA, BANGKOK',type:'COMMERCIAL FESTIVAL',audience:'500 ATTENDEES',reach:'3.8K FOLLOWERS',poster:['rampage-festival.jpg']},
  {date:'17 MAY 2025',name:'ROCK ALARM FESTIVAL 2025',venue:'WAREHOUSE STADIUM · KLONG TOEI, BANGKOK',type:'COMMERCIAL FESTIVAL',audience:'5,000 ATTENDEES',reach:'41K FOLLOWERS',poster:['rock-alarm-1.jpg','rock-alarm-2.jpg']}
 ],international:[
  {date:'07 JUN 2025',name:'櫻擊祭 2025 · PRIMULAV 2025',venue:'MEDIASPHERE THEATER · TAIPEI CITY, TAIWAN',type:'COMMERCIAL FESTIVAL · POWERED BY MAH',audience:'500 ATTENDEES',reach:'3.1K FOLLOWERS',poster:['primulav-2025.jpg']},
  {date:'08 JUN 2025',name:'IDOL CREAM SODA!! × MAH IN TAIWAN',venue:'MEDIASPHERE THEATER · TAIPEI CITY, TAIWAN',type:'COMMERCIAL FESTIVAL',audience:'500 ATTENDEES',reach:'3.1K FOLLOWERS',poster:['idol-cream-soda.jpg']},
  {date:'23–24 AUG 2025',name:'OURSEA CHILL FEST 2025',venue:'MITSUI OUTLET · TAICHUNG, TAIWAN',type:'COMMERCIAL FESTIVAL',audience:'10,000 ATTENDEES',reach:'12.3K FOLLOWERS',poster:['oursea-chill-fest.webp']},
  {date:'10–12 OCT 2025',name:'IDOL KINGDOM 2025',venue:'UNI-PRESIDENT DEPARTMENT STORE / MOONDOG, BREEZE CENTER · TAIPEI, TAIWAN',type:'COMMERCIAL FESTIVAL',audience:'5,000 ATTENDEES',reach:'4K FOLLOWERS',poster:['idol-kingdom-1.webp','idol-kingdom-2.webp']}
 ]}
};
concertData.ja={local:concertData.en.local.map(e=>({...e,type:'商業フェスティバル',audience:e.audience.replace('ATTENDEES','来場者'),reach:e.reach.replace('FOLLOWERS','フォロワー')})),international:concertData.en.international.map(e=>({...e,type:e.type.includes('POWERED')?'商業フェスティバル · POWERED BY MAH':'商業フェスティバル',audience:e.audience.replace('ATTENDEES','来場者'),reach:e.reach.replace('FOLLOWERS','フォロワー')}))};
concertData.zh={
 local:concertData.en.local.map((e,i)=>({...e,date:['2022 年 10 月 15 日','2025 年 3 月 22 日','2025 年 5 月 17 日'][i],venue:['JJ MALL · 泰國曼谷','THE STREET HALL · 曼谷 RATCHADA','WAREHOUSE STADIUM · 曼谷 KLONG TOEI'][i],type:'商業音樂節',audience:e.audience.replace('ATTENDEES','人'),reach:e.reach.replace('FOLLOWERS','追蹤者')})),
 international:concertData.en.international.map((e,i)=>({...e,date:['2025 年 6 月 7 日','2025 年 6 月 8 日','2025 年 8 月 23–24 日','2025 年 10 月 10–12 日'][i],venue:['MEDIASPHERE THEATER · 台灣台北','MEDIASPHERE THEATER · 台灣台北','MITSUI OUTLET · 台灣台中','統一時代百貨／MOONDOG、BREEZE CENTER · 台灣台北'][i],type:e.type.includes('POWERED')?'商業音樂節 · POWERED BY MAH':'商業音樂節',audience:e.audience.replace('ATTENDEES','人'),reach:e.reach.replace('FOLLOWERS','追蹤者')}))
};
let lang=new URLSearchParams(location.search).get('lang')||localStorage.getItem('deadkat-lang')||'th';
if(!copy[lang]) lang='th';
function pick(obj,path){return path.split('.').reduce((v,k)=>v[k],obj)}
function assetPath(src){return src.startsWith('pic/')?`./public/${src}`:`./public/assets/${src}`}
function posterPath(src){return src.startsWith('pic/')?`./public/${src}`:`./public/assets/posters/${src}`}
function render(){document.documentElement.lang=lang==='zh'?'zh-TW':lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=pick(copy[lang],el.dataset.i18n));document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.getElementById('member-list').innerHTML=members.map((m,i)=>`<article class="member-row"><img class="member-photo" src="${assetPath(m.photo)}" alt="${m.name} — DEADKAT"><b>0${i+1}</b><div class="member-id"><strong>${m.name}</strong><span>${m.role}</span></div><div class="social-links"><a href="https://www.instagram.com/${m.handle}/" target="_blank" rel="noreferrer" aria-label="${m.name} Instagram">IG <em>${m.instagram}</em></a><a href="https://www.tiktok.com/@${m.handle}" target="_blank" rel="noreferrer" aria-label="${m.name} TikTok">TT <em>${m.tiktok}</em></a></div></article>`).join('');document.getElementById('records').innerHTML=records[lang].map(([title,desc],i)=>`<a class="record" href="${recordLinks[i]}" target="_blank" rel="noreferrer" aria-label="${title} — Official link"><span class="record-cover"><img src="./public/assets/covers/${recordCovers[i]}" alt="${title} cover"></span><span class="num">0${i+1} / SINGLE</span><h3>${title}</h3><p>${desc}</p><span class="track-cta">${i===5?'LISTEN':'OFFICIAL MV'} ↗</span></a>`).join('');renderDiscographyEditorial();renderPr();renderPressVisual();renderAnalytics();renderConcerts()}
function renderDiscographyEditorial(){const d=discographyEditorial[lang];document.getElementById('discography-editorial').innerHTML=`<div class="discography-copy"><p class="kicker">${d.kicker}</p><h3>${d.title}</h3><p>${d.intro}</p></div><div class="discography-note-grid">${d.notes.map(([title,body],i)=>`<article class="discography-note ${i===6?'performance-note':''}"><span>${i<6?'0'+(i+1)+' / SINGLE':'LIVE / EXPORT DNA'}</span><h4>${title}</h4><p>${body}</p></article>`).join('')}</div>`}
function concertCard(e,i,international=false){return `<article class="concert-card${international?' international-card':''}"><div class="poster-frame ${e.poster.length>1?'poster-pair':''}">${e.poster.map((p,j)=>`<img src="${posterPath(p)}" alt="${e.name} poster${e.poster.length>1?' '+(j+1):''}" loading="lazy">`).join('')}<span>${international?'TAIWAN':'THAILAND'} · 0${i+1}</span></div><div class="concert-details"><time>${e.date}</time><h4>${e.name}</h4><p class="concert-venue">${e.venue}</p><div class="concert-metrics"><span>${e.type}</span><b>${e.audience}</b><b>${e.reach}</b></div></div></article>`}
function renderConcerts(){const d=concertData[lang];document.getElementById('local-concerts').innerHTML=d.local.map((e,i)=>concertCard(e,i)).join('');document.getElementById('international-concerts').innerHTML=d.international.map((e,i)=>concertCard(e,i,true)).join('')}
const prVisuals={
 roadmap:['pr-plan/roadmap-stage-performance-clear.png','pr-plan/canva-crops/roadmap-live-collage.jpg','pic/OSC 1.jpeg','pr-plan/global-merchandise.jpg','pr-plan/thai-textile-fashion.jpg','pr-plan/global-fashion.jpg'],
 detail:['tour/deadkat-live-collage.webp','pic/Sentikissu-may2025.webp','pic/511144381_122173360214368167_6795917288787529317_n.jpg','pr-plan/roadmap-large-group-clear.png'],
 audience:['pr-plan/audience-heart-hands-clear.png','pr-plan/audience-concert-clear.png','pic/GROUP01.jpg','pr-plan/audience-japanese-culture-clear.png'],
 nation:['pr-plan/thai-movement.jpg','pr-plan/thai-textile-fashion.jpg','pr-plan/cat-pants.jpg','pr-plan/cultural-fanmeet.jpg'],
 press:['pr-plan/press-editorials-canva.png','pr-plan/kazz-editorial-clear.png','pr-plan/guitar-mag-clear.jpg']
};
function imageBlock(src,alt,cls=''){return src.endsWith('.mp4')?`<video class="${cls}" controls playsinline preload="metadata" poster="./public/assets/videos/thai-roots-poster.jpg"><source src="./public/${src}" type="video/mp4"></video>`:`<img class="${cls}" src="${assetPath(src)}" alt="${alt}" loading="lazy">`}
function renderPr(){const p=prPlan[lang];document.getElementById('roadmap-grid').innerHTML=p.roadmap.map(([title,body],i)=>`<article class="roadmap-card paired-card"><figure>${imageBlock(prVisuals.roadmap[i],title,(i===3||i===4||i===5)?'contain-visual':'')}</figure><div><span>0${i+1}</span><h4>${title}</h4><p>${body}</p></div></article>`).join('');document.getElementById('roadmap-deck').innerHTML=roadmapDeck[lang].map((card,i)=>`<article class="roadmap-detail-card paired-detail"><figure>${imageBlock(prVisuals.detail[i],card.title,i===3?'contain-visual':'')}</figure><div class="paired-detail-copy"><div><span>${card.tag}</span><h4>${card.title}</h4></div>${card.groups.map(([title,items])=>`<section><h5>${title}</h5><ul>${items.map(item=>`<li>${item}</li>`).join('')}</ul></section>`).join('')}</div></article>`).join('');document.getElementById('audience-grid').innerHTML=p.audience.map(([title,body],i)=>`<article class="audience-card paired-card"><figure>${imageBlock(prVisuals.audience[i],title,i===2?'contain-visual':'')}</figure><div><b>0${i+1}</b><h4>${title}</h4><p>${body}</p></div></article>`).join('');document.getElementById('nation-points').innerHTML=p.nation.map(([title,body],i)=>`<article class="paired-nation"><figure>${imageBlock(prVisuals.nation[i],title,(i===1||i===2)?'contain-visual':'')}</figure><b>0${i+1}</b><div><h4>${title}</h4><p>${body}</p></div></article>`).join('');document.getElementById('press-grid').innerHTML=pressData[lang].map((item,i)=>`<article class="press-card paired-press"><figure>${imageBlock(prVisuals.press[i],item.title,i===0?'press-proof-image':'contain-visual')}</figure><div><span>0${i+1} / ${item.source}</span><time>${item.date}</time><h4>${item.title}</h4><p>${item.body}</p>${item.url?`<a href="${item.url}" target="_blank" rel="noreferrer">READ SOURCE ↗</a>`:''}</div></article>`).join('');const r=riderData[lang];document.getElementById('rider-details').innerHTML=`<div class="rider-meta"><span>${r.engineer}</span></div><div class="rider-columns"><article><h4>STAGE POSITIONS</h4><ul>${r.band.map(x=>`<li>${x}</li>`).join('')}</ul></article><article><h4>MIXER LINE</h4><ul class="input-list">${r.inputs.map(x=>`<li>${x}</li>`).join('')}</ul></article></div><div class="rider-columns rider-equipment"><article><h4>${r.providedTitle}</h4><ul>${r.provided.map(x=>`<li>${x}</li>`).join('')}</ul></article><article><h4>${r.venueTitle}</h4><ul>${r.venue.map(x=>`<li>${x}</li>`).join('')}</ul></article></div><p class="rider-note">${r.note}</p>`}
function renderPressVisual(){}
function renderAnalytics(){const max=Math.max(...streamingData.map(d=>d.total));document.getElementById('song-chart').innerHTML=streamingData.map(d=>`<div class="song-row"><div class="song-meta"><span>${d.name}</span><b>${d.total.toLocaleString()}</b></div><div class="bar-track"><div class="bar-total" style="width:${(d.total/max*100).toFixed(1)}%"><i class="yt" style="width:${(d.yt/d.total*100).toFixed(1)}%"></i><i class="sp" style="width:${(d.sp/d.total*100).toFixed(1)}%"></i><i class="am" style="width:${(d.am/d.total*100).toFixed(1)}%"></i></div></div></div>`).join('');document.getElementById('audience-legend').innerHTML=audienceLabels[lang].map(([name,value],i)=>`<div><i class="aud-${i}"></i><span>${name}</span><b>${value}%</b></div>`).join('')}
function openRecord(i){const [title,body]=records[lang][i];const modal=document.getElementById('record-modal');modal.querySelector('.modal-index').textContent=`0${i+1} / DEADKAT DISCOGRAPHY`;modal.querySelector('h3').textContent=title;modal.querySelector('.modal-body').textContent=body;modal.showModal()}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;localStorage.setItem('deadkat-lang',lang);render()}));
document.querySelector('.menu-toggle').addEventListener('click',e=>{const nav=document.querySelector('.nav');nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',nav.classList.contains('open'))});
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>document.querySelector('.nav').classList.remove('open')));
document.querySelector('.modal-close').addEventListener('click',()=>document.getElementById('record-modal').close());
document.getElementById('year').textContent=new Date().getFullYear();render();
